### ISSUE TITLE
Data dictionary

### ISSUE THREAD

**Issue by lewisjared** [climate-resource/bookshelf#88]
# The problem
As more data gets added we need to be more consistent with how we handle metadata. A data dictionary captures information about a dataset's metadata

This dictionary needs to handle (at minimum) the following aspects for each dimension of metadata:
* description
* type. Options include: string, int, float, date (iso-date formatted)
* Are empty values allowed (default to False to enforce strictness). i.e do all timeseries need to have a non-nan value?
* Is there a controlled vocabulary of options

This information should be added to the yaml file describing the dataset (The `dimensions` attribute isn't currently used so would be added)

```yaml
dimensions:
  - name: variable
    description: Name of the variable
    type: string
    required: True
    controlled_vocabulary:
    - value: Emissions|CO2
      description: CO2 emissions
  - name: hot_air
    description: "The treatment of pathways where targets lack ambition and exceed a reference 'no-additional-climate-policy' emissions scenario"
    type: string
    required: True
    controlled_vocabulary:
    - value: include
      description: "No filtering for “Hot Air" pledged targets is performed. NDCs are used as submitted."
    - value: exclude
      description: "If a pledged target is greater than its “no additional climate policy” reference scenario, the reference scenario for a country is used"
  - name: model_version
    description: Version identifier that describes the version of the software and quantifications that were used.
    type: string
    required: True
```

This would be a minor update to the schema, until we wish to enforce `dimensions` as a required attribute of a datasets metadata.

It would also be trivial to check that a set of timeseries conform to the data dimensions. These checks should be strict i.e. any missing columns fails.

The impact of this would be twofold:
* Stronger consistency across books as the dimensionality of the metadata is explicitly defined
* Error check of books to avoid issues like #20

These metadata dimensions could be rolled up across datasets in future and would be useful search criteria.

# Definition of "done"

* [x] Schema for dimensions added
* [ ] Bump schema version (Have to decide whether this is required for non-breaking changes)
* [ ] Function to check that a dataset conforms to this schema
* [ ] Update primap-hist as a test-case

# Additional context

datapackage's places no requirements on the schema for tabular column data, leaving the decisions to the end user. https://specs.frictionlessdata.io/data-resource/#resource-schemas

Things to also think about:
* How to merge multiple datasets? controlled vocabulary can be merged, but how to treat descriptions (if they don't match).
